apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-config
data:
  topics.sh: |
    #!/bin/bash
    # Create Kafka topics for the malicious text processing pipeline
    
    # Raw topics
    kafka-topics --create --topic raw_tweets_antisemitic --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1
    kafka-topics --create --topic raw_tweets_not_antisemitic --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1
    
    # Processed topics
    kafka-topics --create --topic processed_raw_tweets_antisemitic --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1
    kafka-topics --create --topic processed_raw_tweets_not_antisemitic --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1
    
    # Enriched topics
    kafka-topics --create --topic enriched_preprocessed_tweets_antisemitic --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1
    kafka-topics --create --topic enriched_preprocessed_tweets_not_antisemitic --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-config
data:
  init.js: |
    // Initialize MongoDB collections
    use mydatabase;
    
    // Create collections
    db.createCollection("tweets");
    db.createCollection("antisemitic_collection");
    db.createCollection("not_antisemitic_collection");
    
    // Create indexes
    db.tweets.createIndex({"CreateDate": 1});
    db.antisemitic_collection.createIndex({"CreateDate": 1});
    db.not_antisemitic_collection.createIndex({"CreateDate": 1});